package com.xerox.enterprise.ghs.mmis.rif.rules.blaze;

import org.junit.*;
import static org.junit.Assert.*;
import com.xerox.enterprise.ghs.mmis.rif.common.exception.RIFBlazeRulesException;
import com.xerox.enterprise.ghs.mmis.rif.core.RulesContext;
import com.xerox.enterprise.ghs.mmis.rif.core.RulesResult;

/**
 * The class <code>BlazeRuleInvocationTest</code> contains tests for the class <code>{@link BlazeRuleInvocation}</code>.
 *
 * @generatedBy CodePro at 3/3/15 5:33 PM
 * @author 396662
 * @version $Revision: 1.0 $
 */
public class BlazeRuleInvocationTest {
	/**
	 * Run the BlazeRuleInvocation() constructor test.
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testBlazeRuleInvocation_1()
		throws Exception {
		BlazeRuleInvocation result = new BlazeRuleInvocation();
		assertNotNull(result);
		// add additional test code here
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_1()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_2()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_3()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_4()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_5()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testExecute_6()
		throws Exception {
		RulesContext ctx = new RulesContext();
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
		//       at java.util.ArrayList.rangeCheck(Unknown Source)
		//       at java.util.ArrayList.get(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.execute(BlazeRuleInvocation.java:67)
		assertNotNull(result);
	}

	/**
	 * Run the RulesResult execute(RulesContext,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test(expected = com.xerox.enterprise.ghs.mmis.rif.common.exception.RIFBlazeRulesException.class)
	public void testExecute_7()
		throws Exception {
		RulesContext ctx = null;
		String ruleId = "";

		RulesResult result = BlazeRuleInvocation.execute(ctx, ruleId);

		// add additional test code here
		assertNotNull(result);
	}

	/**
	 * Run the Object getServiceHome(String,Class) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testGetServiceHome_1()
		throws Exception {
		String referenceName = null;
		Class homeInterface = Object.class;

		Object result = BlazeRuleInvocation.getServiceHome(referenceName, homeInterface);

		// add additional test code here
		assertEquals(null, result);
	}

	/**
	 * Run the Object getServiceHome(String,Class) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testGetServiceHome_2()
		throws Exception {
		String referenceName = "";
		Class homeInterface = null;

		Object result = BlazeRuleInvocation.getServiceHome(referenceName, homeInterface);

		// add additional test code here
		assertEquals(null, result);
	}

	/**
	 * Run the Object getServiceHome(String,Class) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testGetServiceHome_3()
		throws Exception {
		String referenceName = "";
		Class homeInterface = Object.class;

		Object result = BlazeRuleInvocation.getServiceHome(referenceName, homeInterface);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at com.acs.enterprise.common.util.service.EnterpriseServiceFactory.getServiceHome(EnterpriseServiceFactory.java:112)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.getServiceHome(BlazeRuleInvocation.java:138)
		assertNotNull(result);
	}

	/**
	 * Run the void initialize() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInitialize_1()
		throws Exception {

		BlazeRuleInvocation.initialize();

		// add additional test code here
	}

	/**
	 * Run the void invalidateCache(String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInvalidateCache_1()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String key = "";
		String caller = "";

		fixture.invalidateCache(key, caller);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.invalidateCache(BlazeRuleInvocation.java:154)
	}

	/**
	 * Run the void invalidateCache(String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInvalidateCache_2()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String key = "";
		String caller = "";

		fixture.invalidateCache(key, caller);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.invalidateCache(BlazeRuleInvocation.java:154)
	}

	/**
	 * Run the void invalidateCache(String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInvalidateCache_3()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String key = "";
		String caller = "";

		fixture.invalidateCache(key, caller);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.invalidateCache(BlazeRuleInvocation.java:154)
	}

	/**
	 * Run the void invalidateCache(String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInvalidateCache_4()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String key = "";
		String caller = "";

		fixture.invalidateCache(key, caller);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.invalidateCache(BlazeRuleInvocation.java:154)
	}

	/**
	 * Run the void invalidateCache(String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testInvalidateCache_5()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String key = "";
		String caller = "";

		fixture.invalidateCache(key, caller);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.invalidateCache(BlazeRuleInvocation.java:154)
	}

	/**
	 * Run the void shutdown() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testShutdown_1()
		throws Exception {

		BlazeRuleInvocation.shutdown();

		// add additional test code here
	}

	/**
	 * Run the void updateCacheMap(String,String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testUpdateCacheMap_1()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String cachekey = "";
		String caller = "";
		String mapKey = "";

		fixture.updateCacheMap(cachekey, caller, mapKey);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.updateCacheMap(BlazeRuleInvocation.java:361)
	}

	/**
	 * Run the void updateCacheMap(String,String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testUpdateCacheMap_2()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String cachekey = "";
		String caller = "";
		String mapKey = "";

		fixture.updateCacheMap(cachekey, caller, mapKey);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.updateCacheMap(BlazeRuleInvocation.java:361)
	}

	/**
	 * Run the void updateCacheMap(String,String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testUpdateCacheMap_3()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String cachekey = "";
		String caller = "";
		String mapKey = "";

		fixture.updateCacheMap(cachekey, caller, mapKey);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.updateCacheMap(BlazeRuleInvocation.java:361)
	}

	/**
	 * Run the void updateCacheMap(String,String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testUpdateCacheMap_4()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String cachekey = "";
		String caller = "";
		String mapKey = "";

		fixture.updateCacheMap(cachekey, caller, mapKey);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.updateCacheMap(BlazeRuleInvocation.java:361)
	}

	/**
	 * Run the void updateCacheMap(String,String,String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Test
	public void testUpdateCacheMap_5()
		throws Exception {
		BlazeRuleInvocation fixture = new BlazeRuleInvocation();
		String cachekey = "";
		String caller = "";
		String mapKey = "";

		fixture.updateCacheMap(cachekey, caller, mapKey);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at java.util.StringTokenizer.<init>(Unknown Source)
		//       at com.xerox.enterprise.ghs.mmis.rif.rules.blaze.BlazeRuleInvocation.updateCacheMap(BlazeRuleInvocation.java:361)
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 3/3/15 5:33 PM
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(BlazeRuleInvocationTest.class);
	}
}