package com.xerox.ghs.mmis.rif.examples;

import org.junit.*;
import static org.junit.Assert.*;

/**
 * The class <code>RIFClientProviderTest</code> contains tests for the class <code>{@link RIFClientProvider}</code>.
 *
 * @generatedBy CodePro at 5/5/14 6:05 PM
 * @author 396662
 * @version $Revision: 1.0 $
 */
public class RIFClientProviderTest {
	/**
	 * Run the RIFClientProvider() constructor test.
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@Test
	public void testRIFClientProvider_1()
		throws Exception {
		RIFClientProvider result = new RIFClientProvider();
		assertNotNull(result);
		// add additional test code here
	}

	/**
	 * Run the void invokeProviderPOJO() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@Test
	public void testInvokeProviderPOJO_1()
		throws Exception {
		RIFClientProvider fixture = new RIFClientProvider();

		fixture.invokeProviderPOJO();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NoClassDefFoundError: Could not initialize class com.xerox.ghs.mmis.rif.core.RuleHandler
		//       at com.xerox.ghs.mmis.rif.examples.RIFClientProvider.invokeProviderPOJO(RIFClientProvider.java:60)
	}

	/**
	 * Run the void invokeProviderPOJO() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@Test
	public void testInvokeProviderPOJO_2()
		throws Exception {
		RIFClientProvider fixture = new RIFClientProvider();

		fixture.invokeProviderPOJO();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NoClassDefFoundError: Could not initialize class com.xerox.ghs.mmis.rif.core.RuleHandler
		//       at com.xerox.ghs.mmis.rif.examples.RIFClientProvider.invokeProviderPOJO(RIFClientProvider.java:60)
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@Test
	public void testMain_1()
		throws Exception {
		String[] args = new String[] {};

		RIFClientProvider.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.ExceptionInInitializerError
		//       at com.xerox.ghs.mmis.rif.examples.RIFClientProvider.invokeProviderPOJO(RIFClientProvider.java:60)
		//       at com.xerox.ghs.mmis.rif.examples.RIFClientProvider.main(RIFClientProvider.java:22)
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 5/5/14 6:05 PM
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(RIFClientProviderTest.class);
	}
}